name: Deploy Astro Site to GitHub Pages

on:
    push:
        branches:
            - main # Change this to your main branch name

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: "20"

            - name: Install dependencies
              run: npm ci --force

            - name: Build Astro site
              run: npm run build # Adjust the build command if necessary

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./dist # Update this to the directory where Astro generates the build output
                  force_orphan: true # This will force-push to the gh-pages branch

